name: Tests
on:
  # Lancement du workflow à chaque push sur la branche main
  push:
    branches: [ "main" ]

  # Autorisation de lancer manuellement le workflow
  workflow_dispatch:

# Actions du workflow
jobs:
  # Tests du système
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Maven wrapper
        run: chmod +x ./api/mvnw

      # Compilation de l'api
      - name: install api
        run: ./mvnw clean install
        working-directory: ./api
      
      # Test l'api
      - name: tests api
        run: ./mvnw clean verify
        working-directory: ./api

      - name: Grant execute permission for Maven wrapper
        run: chmod +x ./webapp/mvnw
        
      # Test l'application web
      - name: test webapp
        run: ./mvnw clean verify
        working-directory: ./webapp
